<?php
/**
 * Class OmniQuill_Context_Engine
 * * Handles auxiliary data processing: Image serialization,
 * Web Scraping, and Google Search integration.
 */
class OmniQuill_Context_Engine {

    public static function get_image_base64( $media_id ) {
        $path = get_attached_file( $media_id );
        if ( ! file_exists( $path ) ) return new WP_Error( 'file_not_found', 'Image file missing.' );

        $type = get_post_mime_type( $media_id );
        $data = file_get_contents( $path );
        return [
            'base64' => base64_encode( $data ),
            'mime'   => $type
        ];
    }

    public static function upload_generated_image( $base64, $mime, $prompt ) {
        $binary = base64_decode( $base64 );
        $upload_dir = wp_upload_dir();
        $filename = 'omni-gen-' . time() . '.png';
        $file_path = $upload_dir['path'] . '/' . $filename;

        file_put_contents( $file_path, $binary );

        $attachment = [
            'post_mime_type' => $mime,
            'post_title'     => $prompt,
            'post_content'   => 'Generated by OmniQuill',
            'post_status'    => 'inherit'
        ];

        $attach_id = wp_insert_attachment( $attachment, $file_path );
        if ( is_wp_error( $attach_id ) ) return $attach_id;

        require_once( ABSPATH . 'wp-admin/includes/image.php' );
        $attach_data = wp_generate_attachment_metadata( $attach_id, $file_path );
        wp_update_attachment_metadata( $attach_id, $attach_data );

        return [ 'id' => $attach_id, 'url' => wp_get_attachment_url( $attach_id ) ];
    }

    public static function scrape_url( $url ) {
        $res = wp_remote_get( $url, [ 'timeout' => 15 ] );
        if ( is_wp_error( $res ) ) return '';

        $body = wp_remote_retrieve_body( $res );
        if ( empty( $body ) ) return '';

        $dom = new DOMDocument();
        @$dom->loadHTML( $body );

        // Remove noise
        foreach ( $dom->getElementsByTagName( 'script' ) as $s ) $s->parentNode->removeChild( $s );
        foreach ( $dom->getElementsByTagName( 'style' ) as $s ) $s->parentNode->removeChild( $s );

        $content = trim( substr( $dom->textContent, 0, 5000 ) );
        return "\n\nhttps://docs.cloud.google.com/vertex-ai/generative-ai/docs/url-context:\n" . $content;
    }

    public static function perform_web_search( $query, $key, $cx ) {
        $url = "https://www.googleapis.com/customsearch/v1?key=$key&cx=$cx&q=" . urlencode( $query );
        $res = wp_remote_get( $url );

        if ( is_wp_error( $res ) ) return '';

        $body = json_decode( wp_remote_retrieve_body( $res ), true );
        if ( empty( $body['items'] ) ) return '';

        $out = "\n\n[WEB SEARCH RESULTS]:\n";
        foreach ( array_slice( $body['items'], 0, 4 ) as $item ) {
            $out .= "- " . ( $item['title'] ?? '' ) . ": " . ( $item['snippet'] ?? '' ) . "\n";
        }
        return $out;
    }
}
